#!/bin/bash

echo "Starting Document Processing System containers..."

docker compose up -d --build

echo "All containers are now running"
echo "➡ API will be available at: http://localhost:8080"
echo "➡ phpMyAdmin: http://localhost:8081"
