#!/bin/bash

echo "Starting Document Processing System containers..."

docker compose up -d --build

echo "➡ Installing Composer dependencies..."
docker exec dps_app composer install --no-interaction --prefer-dist

echo "➡ API will be available at: http://localhost:8080"
echo "➡ phpMyAdmin will be available at: http://localhost:8081"
echo "➡ Telescope will be available at: http://localhost:8080/telescope"
